// ========== FOTOS DE CHILE ==========
var nortePhotos = [
    { name:'Piedras Rojas', url:'https://drive.google.com/thumbnail?id=1F0IYAE6mROqz0nBtOrRL0-r-7xMQFwhb&sz=w400', zone:'norte', nota:'Formaciones rocosas en el altiplano, a más de 4.000m.' },
    { name:'Laguna Miscanti', url:'https://drive.google.com/thumbnail?id=1UQtlAR9wOdNBsC-E2XnYpLEbCXPDGtsA&sz=w400', zone:'norte', nota:'Laguna altiplánica en Antofagasta.' },
    { name:'Valle de la Luna', url:'https://drive.google.com/thumbnail?id=14Od2N2_ZkM4avnh1UiOHI6U3gqeMxLny&sz=w400', zone:'norte', nota:'Paisaje lunar en el Desierto de Atacama.' },
    { name:'Iglesia', url:'https://drive.google.com/thumbnail?id=1CU-oHqUlBsoeit8D7THQCnvdzeE3Ri0o&sz=w400', zone:'norte', nota:'San Pedro de Atacama.' },
    { name:'Flamenco', url:'https://drive.google.com/thumbnail?id=14Qdu0r0OuSeZgFb9-Nz1VSq0ytx_SqG1&sz=w400', zone:'norte', nota:'Fauna en el Salar de Atacama.' },
    { name:'La Portada', url:'https://drive.google.com/thumbnail?id=1cLUas6xEls2ZgtyI14qiX04KLDjroqcG&sz=w400', zone:'norte', nota:'Región de Antofagasta.' },
    { name:'Lagunas Escondidas', url:'https://drive.google.com/thumbnail?id=1dKEA6oYUsiEXfE5Yf2-Yp8Eu0f6baMvK&sz=w400', zone:'norte', nota:'Salar de Atacama.' },
    { name:'Desierto Florido', url:'https://drive.google.com/thumbnail?id=1zw6EbP5jjmpuM6izdhL9GTbrUPv2_pEg&sz=w400', zone:'norte', nota:'La magia del desierto chileno.' },
    { name:'Géiser del Tatio', url:'https://drive.google.com/thumbnail?id=1myfk3mUjy78mLbMvSe1pjdXw8uvRism-&sz=w400', zone:'norte', nota:'Aguas termales a más de 4.300m.' },
    { name:'Valle del Arcoíris', url:'https://drive.google.com/thumbnail?id=1glWxef_1S66sAAIwemQx1_KXEnPKwtam&sz=w400', zone:'norte', nota:'Cerros multicolores.' },
    { name:'Lagunas Altiplánicas', url:'https://drive.google.com/thumbnail?id=19R2ZGOtvO9iOcLhOtVcTpDATOb4igup6&sz=w400', zone:'norte', nota:'Lagunas de altura en Antofagasta.' },
    { name:'Salar de Atacama', url:'https://drive.google.com/thumbnail?id=1grEzPHz96h3nI3Am8DRBbdN3PFs71-or&sz=w400', zone:'norte', nota:'El mayor salar de Chile.' },
];
var centroPhotos = [
    { name:'Costanera Center', url:'https://drive.google.com/thumbnail?id=1nGUkO0nawN3gOwjW21hXCIDNYPFegMt0&sz=w400', zone:'centro', nota:'Vista panorámica del centro.' },
    { name:'Castillo Wulff', url:'https://drive.google.com/thumbnail?id=1yv2VBxXp9gu27IFAm5tN-IiumJ7sspBe&sz=w400', zone:'centro', nota:'Viña del Mar.' },
    { name:'Cerro San Cristobal', url:'https://drive.google.com/thumbnail?id=1HCxBgrT5lDyhSLe2otrp4w2ugBBDXSbX&sz=w400', zone:'centro', nota:'Santiago.' },
    { name:'Cerro Santa Lucía', url:'https://drive.google.com/thumbnail?id=1R-r4Tt1TIc9A7VJ1_-_iXy2P2NpZfOsN&sz=w400', zone:'centro', nota:'Santiago.' },
    { name:'Cordillera de Los Andes', url:'https://drive.google.com/thumbnail?id=1Vy-KF3PCdLQTPg-9grzLVjyWTebzlCHb&sz=w400', zone:'centro', nota:'Hermosa vista desde la capital.' },
    { name:'Atardecer Santiago', url:'https://drive.google.com/thumbnail?id=1PyuMXVS-J7z4Ch1u3mFt27E6wmkpEK5L&sz=w400', zone:'centro', nota:'Con la cordillera de fondo.' },
    { name:'Embalse El Yeso', url:'https://drive.google.com/thumbnail?id=1Ay1YRncILC0rm0QZM_cEn2Vodu23cOCd&sz=w400', zone:'centro', nota:'Cajón del Maipo.' },
    { name:'Centro de Santiago', url:'https://drive.google.com/thumbnail?id=1VqAz0OrJZ3kufu5_yj7M6zs1NgUy6Byw&sz=w400', zone:'centro', nota:'Zona urbana de comercio.' },
    { name:'Barrio Lastarria', url:'https://drive.google.com/thumbnail?id=16yL_2czoYeGo8Ps0yq2eAunMaMnx2e0F&sz=w400', zone:'centro', nota:'Lugar de encuentro de artistas.' },
    { name:'Viñedos', url:'https://drive.google.com/thumbnail?id=1xFEIBTub8gBh1W5KRq2_ZBiUNmrFFJnH&sz=w400', zone:'centro', nota:'Valle Central.' },
    { name:'Parque La Campana', url:'https://drive.google.com/thumbnail?id=1j6zc5a3Fs66WF4RNzL8CS0DxNrgeH9ll&sz=w400', zone:'centro', nota:'Reserva de la biosfera en Valparaíso.' },
    { name:'Caleta Horcón', url:'https://drive.google.com/thumbnail?id=1891kWifKa-U9pkBRtkPRtmpR09IRPpsm&sz=w400', zone:'centro', nota:'Pueblo costero con tradición pesquera.' },
];
var surPhotos = [
    { name:'Palafitos', url:'https://drive.google.com/thumbnail?id=1AmW36m9FQyk4YCmIIl4jT_pML24l5p8d&sz=w400', zone:'sur', nota:'Castro Chiloé.' },
    { name:'Rio Calle Calle', url:'https://drive.google.com/thumbnail?id=120O2TkWrtd-pJnsCqv6ktR3Z-kXZ_37i&sz=w400', zone:'sur', nota:'Valdivia.' },
    { name:'Volcán Villarrica', url:'https://drive.google.com/thumbnail?id=1X-7YtR48yGYGfRasz4mLOgnx8RsXPCPC&sz=w400', zone:'sur', nota:'Hermosa vista desde Pucón.' },
    { name:'Río Tolten', url:'https://drive.google.com/thumbnail?id=1yR4_putOUKXtkjcFUp4j680VCMiZpB6b&sz=w400', zone:'sur', nota:'Región de la Araucanía.' },
    { name:'Selva valdiviana', url:'https://drive.google.com/thumbnail?id=1CfegotOgyuSQ_3LpVQRYUeFOgcepX8jB&sz=w400', zone:'sur', nota:'Región de los Ríos.' },
    { name:'Volcán Osorno', url:'https://drive.google.com/thumbnail?id=1qHxn6xYIMKduZ55urTczocbY8pQo6fL0&sz=w400', zone:'sur', nota:'Saltos de Petrohue.' },
    { name:'Puerto Varas', url:'https://drive.google.com/thumbnail?id=1c8lbpmfV_tPnO7RFu_BJ4wWJMgIgAeue&sz=w400', zone:'sur', nota:'Lago Llanquihue.' },
    { name:'Mercado fluvial', url:'https://drive.google.com/thumbnail?id=1t0G1sHMmV0EfZFa3J2wlpW6qzb2Zexai&sz=w400', zone:'sur', nota:'Valdivia.' },
    { name:'Martin pescador', url:'https://drive.google.com/thumbnail?id=1MDDIDV3T6IOPgE5tXsF0TgP_ZBun-xhK&sz=w400', zone:'sur', nota:'Fauna del sur.' },
    { name:'Volcán Lonquimay', url:'https://drive.google.com/thumbnail?id=1Y1KoBuViE5kXhMI8jXs0NptFhYQcRlgS&sz=w400', zone:'sur', nota:'Reserva Nacional Malalcahuello.' },
    { name:'Puente Bastidas', url:'https://drive.google.com/thumbnail?id=1uovAMwK7ud7r3byH3y31ESh2-_z6Uuup&sz=w400', zone:'sur', nota:'Rio Tolten Villarrica.' },
    { name:'Viaducto del Malleco', url:'https://drive.google.com/thumbnail?id=15HOHLT2otsmj5AJ5pDmv5k8h3VtlzjSC&sz=w400', zone:'sur', nota:'Región de la Araucanía.' },
];
var patagoniaPhotos = [
    { name:'Torres del Paine', url:'https://drive.google.com/thumbnail?id=15ax4Kz362p7z5yTjbgd8z9b98ha3HfTh&sz=w400', zone:'austral', nota:'Puerto Natales.' },
    { name:'Punta Arenas', url:'https://drive.google.com/thumbnail?id=18bTBxQKTjcVHaBdkZpPh967esE5MD1PL&sz=w400', zone:'austral', nota:'Región de Magallanes.' },
    { name:'Lago Grey', url:'https://drive.google.com/thumbnail?id=1-o2SJrZDqQE64vESRbYExBcEH1lzHaPW&sz=w400', zone:'austral', nota:'Torres del Paine.' },
    { name:'Glaciar Grey', url:'https://drive.google.com/thumbnail?id=1_VLPDVx6WBuBiA4hEegwtLWGZJ285DMB&sz=w400', zone:'austral', nota:'Hielo azul eterno.' },
    { name:'Valle del Francés', url:'https://drive.google.com/thumbnail?id=1tVxHCA0R_4f4apJse_hvco32R0nVHc3R&sz=w400', zone:'austral', nota:'Paisajes increíbles.' },
    { name:'Estancia Patagónica', url:'https://drive.google.com/thumbnail?id=1cY0MZt2mekm40M0lynkh6CypXNX4PZ-G&sz=w400', zone:'austral', nota:'La soledad más bella del planeta.' },
    { name:'Lago Pehoé', url:'https://drive.google.com/thumbnail?id=1NpBgGLaGErifAqGG0m5cjJR2zfmB07x7&sz=w400', zone:'austral', nota:'Estepa y montaña.' },
    { name:'Canal Beagle', url:'https://drive.google.com/thumbnail?id=1Y--szySJeRA54gtRZgMWX2rXLoURu654&sz=w400', zone:'austral', nota:'Ríos de hielo.' },
    { name:'Cabo de Hornos', url:'https://drive.google.com/thumbnail?id=1exOBlMQYYveF6J02irHIofpI2nUo9U7A&sz=w400', zone:'austral', nota:'La Patagonia profunda.' },
    { name:'Isla Magdalena', url:'https://drive.google.com/thumbnail?id=1awWCm8OHQ2vUPdR1-1XVSyqBXKXDIopk&sz=w400', zone:'austral', nota:'Colores imposibles.' },
    { name:'Puerto Williams', url:'https://drive.google.com/thumbnail?id=1YUC001Cd2vKwxNyV1ri1nlcDcQY3yxip&sz=w400', zone:'austral', nota:'Tierra de gigantes y leyendas.' },
    { name:'Ventisquero Colgante', url:'https://drive.google.com/thumbnail?id=1PQ9x8ocUO_H2l7QmCHguro8M0HJS4aPW&sz=w400', zone:'austral', nota:'Glaciar colgante en la Patagonia chilena.' },
];
var argentinaNortePhotos = [
    { name:'Quebrada de Humahuaca', url:'https://drive.google.com/thumbnail?id=1uwaDZGOxkdgwZh-Xb3kDYdjB7BVHEVyh&sz=w400', zone:'argentina-norte', nota:'Patrimonio de la Humanidad en Jujuy.' },
    { name:'Cerro 7 Colores', url:'https://drive.google.com/thumbnail?id=1xGdn2yjxwquDyAQKBsmg9INXr4NomCzk&sz=w400', zone:'argentina-norte', nota:'Ícono de Purmamarca, Jujuy.' },
    { name:'Salinas Grandes', url:'https://drive.google.com/thumbnail?id=1xGdn2yjxwquDyAQKBsmg9INXr4NomCzk&sz=w400', zone:'argentina-norte', nota:'Desierto de sal.' },
    { name:'Cuesta de Lipán', url:'https://drive.google.com/thumbnail?id=16NaOVDOdGL_5bO5e9Rzco76T28hcId_W&sz=w400', zone:'argentina-norte', nota:'Carretera de montaña.' },
    { name:'Pucará de Tilcara', url:'https://drive.google.com/thumbnail?id=1iOlTgQKYeUv8CmL5eo_Xji-c0x19NTX8&sz=w400', zone:'argentina-norte', nota:'Fortaleza prehispánica.' },
    { name:'Cafayate', url:'https://drive.google.com/thumbnail?id=1JoGF-I8Tjy6xJ0YlO1THzJKMPqrNytBk&sz=w400', zone:'argentina-norte', nota:'Tierra de viñedos en Salta.' },
    { name:'Tren a las Nubes', url:'https://drive.google.com/thumbnail?id=168XM8s329lphZbPB8lWBu_EzdtUHJgV6&sz=w400', zone:'argentina-norte', nota:'Recorrido ferroviario a más de 4.000m.' },
    { name:'Ruinas de Quilmes', url:'https://drive.google.com/thumbnail?id=1b217TXK5tARb4E5ha8gpOJsqd1J-MAjK&sz=w400', zone:'argentina-norte', nota:'Restos de la civilización diaguita.' },
    { name:'Piedra Pómez', url:'https://drive.google.com/thumbnail?id=1hkSjwTHKIeiTc7SSUQX-3mMJ0IYHry4r&sz=w400', zone:'argentina-norte', nota:'Paisaje lunar en Catamarca.' },
    { name:'Volcán Llullaillaco', url:'https://drive.google.com/thumbnail?id=160i15aGgwKQUp9zvFkF97QsdQYaXsJO_&sz=w400', zone:'argentina-norte', nota:'Uno de los volcanes más altos.' },
    { name:'Museo de Arqueología', url:'https://drive.google.com/thumbnail?id=1SbJeLKXcy3GJIC3BIPqcWFMAtJFcqu1t&sz=w400', zone:'argentina-norte', nota:'Hogar de los Niños de Llullaillaco.' },
    { name:'Termas de Reyes', url:'https://drive.google.com/thumbnail?id=1V4iPmI3BV6VfCrl6a391vg7pGdXoiySI&sz=w400', zone:'argentina-norte', nota:'Aguas termales en Jujuy.' },
];
var argentinaCentroPhotos = [
    { name:'Obelisco', url:'https://drive.google.com/thumbnail?id=10ZOMdYNbi5kOhyMKx5eHkkjNZUm_jl6I&sz=w400', zone:'argentina-centro', nota:'Ícono de Buenos Aires, 1936.' },
    { name:'Barrio La Boca', url:'https://drive.google.com/thumbnail?id=1zrmqqgnLiZyi5ZWeCNtL_MkdPX_h6PsI&sz=w400', zone:'argentina-centro', nota:'Casas de colores y tango.' },
    { name:'Mar del Plata', url:'https://drive.google.com/thumbnail?id=10sHvR-SShb3lgvR7Bdn6cUt_xWdEijPz&sz=w400', zone:'argentina-centro', nota:'Playas de la costa atlántica.' },
    { name:'Sierras de Córdoba', url:'https://drive.google.com/thumbnail?id=1kR5_cjsNN0pQC-J3BrhBKIBI-Bq9s8bU&sz=w400', zone:'argentina-centro', nota:'Paisaje serrano.' },
    { name:'Bodega Mendoza', url:'https://drive.google.com/thumbnail?id=1WvP8y01OhQ_mpCxaIzwUuXyNE4GT7Kun&sz=w400', zone:'argentina-centro', nota:'Ruta del vino en Cuyo.' },
    { name:'Cerro de la Gloria', url:'https://drive.google.com/thumbnail?id=1HC3JynlYZZ1SuR-51nO7jJhCisDxx97x&sz=w400', zone:'argentina-centro', nota:'Monumento histórico en Mendoza.' },
    { name:'Teatro Colón', url:'https://drive.google.com/thumbnail?id=1Rw51ZPGayYMNoGgXVkSkvl9yYkwpVaGe&sz=w400', zone:'argentina-centro', nota:'Teatro de ópera.' },
    { name:'Puente Colgante', url:'https://drive.google.com/thumbnail?id=1IrFr17SSrT_yh4exd19gse-IKkSKM2du&sz=w400', zone:'argentina-centro', nota:'Ícono de Santa Fe.' },
    { name:'Reloj Cucú', url:'https://drive.google.com/thumbnail?id=1NA9uzV_uaF9ri3HbF_ZAVdWnuk_VpXgp&sz=w400', zone:'argentina-centro', nota:'Atracción de La Falda, Córdoba.' },
    { name:'Bosques de Palermo', url:'https://drive.google.com/thumbnail?id=1uIr44S0CaPur3-w64phRPawwL9leVn0Z&sz=w400', zone:'argentina-centro', nota:'Pulmón verde de Buenos Aires.' },
    { name:'Catedral de Salta', url:'https://drive.google.com/thumbnail?id=1lkzlryApUwl3UiTqIUJLqNVOCX3h-_BI&sz=w400', zone:'argentina-centro', nota:'Arquitectura colonial.' },
    { name:'Cabildo de Buenos Aires', url:'https://drive.google.com/thumbnail?id=1Hhm3aqA4654w9zRqGGEOkcpNhBNZk6qj&sz=w400', zone:'argentina-centro', nota:'Histórico edificio colonial.' },
];
var argentinaPatagoniaPhotos = [
    { name:'Glaciar Perito Moreno', url:'https://drive.google.com/thumbnail?id=1CpP4mNkUsguTJc3ogku5O_rFvznW3oOl&sz=w400', zone:'argentina-patagonia', nota:'El glaciar más famoso de Argentina.' },
    { name:'Ushuaia', url:'https://drive.google.com/thumbnail?id=1mhDWXZwJMPdRmuMSMmmFjagu0HrYrheu&sz=w400', zone:'argentina-patagonia', nota:'La ciudad más austral del mundo.' },
    { name:'Cerro Chaltén', url:'https://drive.google.com/thumbnail?id=1qfmMulhoOaDGYTBDAyX7tc9NOLgiactp&sz=w400', zone:'argentina-patagonia', nota:'Imponente montaña patagónica.' },
    { name:'Bariloche', url:'https://drive.google.com/thumbnail?id=1Tny2syXcCZbm-GzlTT10I6MsQ_QjA6uW&sz=w400', zone:'argentina-patagonia', nota:'Lagos y montañas en Río Negro.' },
    { name:'Cueva de las Manos', url:'https://drive.google.com/thumbnail?id=1thIyH39oAdz1xMuMVaGz_kzLgbN8T4fQ&sz=w400', zone:'argentina-patagonia', nota:'Pinturas rupestres de más de 9.000 años.' },
    { name:'Puerto Madryn', url:'https://drive.google.com/thumbnail?id=1DJ4I59mDo4ezdBpmtwtihRao9aB62_cy&sz=w400', zone:'argentina-patagonia', nota:'Avistaje de ballenas en Chubut.' },
    { name:'Tren Fin del Mundo', url:'https://drive.google.com/thumbnail?id=13fSVdYz8QQCMlpfuL0zI6hKBFL_akKPN&sz=w400', zone:'argentina-patagonia', nota:'Ferrocarril histórico en Ushuaia.' },
    { name:'Lago Argentino', url:'https://drive.google.com/thumbnail?id=1vOIHBROl5MttXEkydQjd-zPTAVavugpO&sz=w400', zone:'argentina-patagonia', nota:'El lago más grande de Argentina.' },
    { name:'Bosque Petrificado', url:'https://drive.google.com/thumbnail?id=1KvTg6KlQu_yasKc93hVY5vc0jQt-r-DC&sz=w400', zone:'argentina-patagonia', nota:'Restos fósiles en Santa Cruz.' },
    { name:'El Calafate', url:'https://drive.google.com/thumbnail?id=1qMcxmtSV4WUmtBtg7m9u8CpsuOg1a9DQ&sz=w400', zone:'argentina-patagonia', nota:'Puerta de entrada al Perito Moreno.' },
    { name:'Cerro Tronador', url:'https://drive.google.com/thumbnail?id=1R2sw4o75kemK39snxurKc-AtX_8VA7r-&sz=w400', zone:'argentina-patagonia', nota:'Montaña con glaciares colgantes.' },
    { name:'Punta Tombo', url:'https://drive.google.com/thumbnail?id=1EVi3-6eyImqmdGu_11bBBEg42XC4Fs61&sz=w400', zone:'argentina-patagonia', nota:'La colonia de pingüinos más grande.' },
];
var argentinaLitoralPhotos = [
    { name:'Cataratas del Iguazú', url:'https://drive.google.com/thumbnail?id=1OuzQI_YpKYOVwc9KwRwNmXN6OdCjRtTW&sz=w400', zone:'argentina-litoral', nota:'Maravilla natural en Misiones.' },
    { name:'Parque Talampaya', url:'https://drive.google.com/thumbnail?id=1uxxaHlPhEaU4bAl4uVUL9rmHlm79ZMmh&sz=w400', zone:'argentina-litoral', nota:'Formaciones rocosas en La Rioja.' },
    { name:'Ruinas de San Ignacio', url:'https://drive.google.com/thumbnail?id=1jRCowaPfltVWht7n-v_6PdEhua3YpFXt&sz=w400', zone:'argentina-litoral', nota:'Misiones jesuíticas en Misiones.' },
    { name:'Puerto Iguazú', url:'https://drive.google.com/thumbnail?id=1Frz-zvaqu72Jzw3s6Y687JtVCrVclEz2&sz=w400', zone:'argentina-litoral', nota:'Ciudad fronteriza.' },
    { name:'Costanera de Rosario', url:'https://drive.google.com/thumbnail?id=1OeE1B0kFzgggFyWevpQyIF_IdHGV_dSV&sz=w400', zone:'argentina-litoral', nota:'Paseo junto al río Paraná.' },
    { name:'Parque El Palmar', url:'https://drive.google.com/thumbnail?id=1s_E0F1wrwNBEHaIcjt7L0dO1P6tcXraM&sz=w400', zone:'argentina-litoral', nota:'Palmeras yatay en Entre Ríos.' },
    { name:'Termas de Colón', url:'https://drive.google.com/thumbnail?id=1WWCbcu93lI3lUlXRJQdsoWIEL9oUP74i&sz=w400', zone:'argentina-litoral', nota:'Aguas termales en Entre Ríos.' },
    { name:'Esteros del Iberá', url:'https://drive.google.com/thumbnail?id=1yLmtbooXH-0mtJdC4lHPsd90bqrj3d10&sz=w400', zone:'argentina-litoral', nota:'Humedales y fauna en Corrientes.' },
    { name:'Basílica de Luján', url:'https://drive.google.com/thumbnail?id=11jON7WP6SKzhhwrBT5kyc_B36EA1oSXA&sz=w400', zone:'argentina-litoral', nota:'Santuario católico en Buenos Aires.' },
    { name:'Monumento a la Bandera', url:'https://drive.google.com/thumbnail?id=1e8iXmJwVlPv-PogjsexcSjODR5wnZKq5&sz=w400', zone:'argentina-litoral', nota:'Ícono de la ciudad de Rosario.' },
    { name:'Puente Rosario-Victoria', url:'https://drive.google.com/thumbnail?id=1HDySZD2cL6j_zUKtAwrDZ3Ooy_FivXiv&sz=w400', zone:'argentina-litoral', nota:'Conecta Rosario con Victoria.' },
    { name:'Mina Wanda', url:'https://drive.google.com/thumbnail?id=1ZZNrOEqdcVIT_sbdr57FkeeEnOZJcls6&sz=w400', zone:'argentina-litoral', nota:'Mina de piedras preciosas en Misiones.' },
];
var mexicoNortePhotos = [
    { name:'Cañón del Cobre', url:'https://drive.google.com/thumbnail?id=11iYN2ZNRxF6jSGqL2kq5euBNLniu_Qqw&sz=w400', zone:'mexico-norte', nota:'Sistema de cañones en Chihuahua.' },
    { name:'Dunas de Samalayuca', url:'https://drive.google.com/thumbnail?id=1dAzA4IjDqVzn4X5VdGXgmfywYmHS5ntk&sz=w400', zone:'mexico-norte', nota:'Imponentes dunas en Chihuahua.' },
    { name:'Cascada Basaseachi', url:'https://drive.google.com/thumbnail?id=1EgLFXZgc_J8vbapy49cnMxEzhxyph3lF&sz=w400', zone:'mexico-norte', nota:'La cascada más alta de México.' },
    { name:'Sierra del Carmen', url:'https://drive.google.com/thumbnail?id=1z0lvQo__xxUZIiUDJVTOV7Pqoto3EFJd&sz=w400', zone:'mexico-norte', nota:'Reserva natural en Coahuila.' },
    { name:'Cumbres de Monterrey', url:'https://drive.google.com/thumbnail?id=17v9d89qxcwarJt1KnjlSN4MQ-Oa3xbx-&sz=w400', zone:'mexico-norte', nota:'Montañas en Nuevo León.' },
    { name:'Grutas de García', url:'https://drive.google.com/thumbnail?id=1GNOu7WhWT21V2Nmbb5NGODSdVQ3OBah9&sz=w400', zone:'mexico-norte', nota:'Cuevas en Nuevo León.' },
    { name:'Valle Fantasmas', url:'https://drive.google.com/thumbnail?id=1IIPmf-hcvKGmKeB8Uq6p6n38DSR5EI_Z&sz=w400', zone:'mexico-norte', nota:'Formaciones rocosas únicas.' },
    { name:'Zona del Silencio', url:'https://drive.google.com/thumbnail?id=1CNLEvaIPuMohelHfZPR2bZ0JaJuxvv6Z&sz=w400', zone:'mexico-norte', nota:'Área desértica en Durango.' },
    { name:'Puente Baluarte', url:'https://drive.google.com/thumbnail?id=17743PcwVJF8hXz-Kjqcwx1DWDR-C0PnA&sz=w400', zone:'mexico-norte', nota:'Puente atirantado más alto de América.' },
    { name:'Isla Tiburón', url:'https://drive.google.com/thumbnail?id=16YR-PBB-Mlovp-T6UCpsGrUM3aeHOSRw&sz=w400', zone:'mexico-norte', nota:'La isla más grande de México.' },
    { name:'Desierto de Altar', url:'https://drive.google.com/thumbnail?id=1aNchwj76SLEtXEteKqItWqtLFI70pTLX&sz=w400', zone:'mexico-norte', nota:'Vasto desierto en Sonora.' },
    { name:'Creel', url:'https://drive.google.com/thumbnail?id=1hfZpv99DoeOXjtvyOVrfs6BZrZMQcVoL&sz=w400', zone:'mexico-norte', nota:'Pueblo Mágico en la Sierra Tarahumara.' },
];
var mexicoCentroPhotos = [
    { name:'Zócalo CDMX', url:'https://drive.google.com/thumbnail?id=1C8XZ_N5u8Ajtpl6i9kQ0zr3zycifaGN7&sz=w400', zone:'mexico-centro', nota:'Plaza principal de la Ciudad de México.' },
    { name:'Bellas Artes', url:'https://drive.google.com/thumbnail?id=1WI5QZB_qHtzD_RX5NgHZza4VWfJWqrH0&sz=w400', zone:'mexico-centro', nota:'Ícono cultural de CDMX.' },
    { name:'Xochimilco', url:'https://drive.google.com/thumbnail?id=1VsZs5alPe9h7xHeYfiHGbsx6Mr54KVBT&sz=w400', zone:'mexico-centro', nota:'Canales y trajineras.' },
    { name:'Basílica de Guadalupe', url:'https://drive.google.com/thumbnail?id=1mPie5m_w8rcyqeiHN393qhC2vHQhHP8C&sz=w400', zone:'mexico-centro', nota:'Santuario mariano más visitado.' },
    { name:'Teotihuacán', url:'https://drive.google.com/thumbnail?id=1CmNy4rANRzEuN78LUeyjmdGvjlgZZJBL&sz=w400', zone:'mexico-centro', nota:'Antigua ciudad de pirámides.' },
    { name:'Taxco', url:'https://drive.google.com/thumbnail?id=1iuaj-mliBGXKYYaIc94_juUUVZDEK8WV&sz=w400', zone:'mexico-centro', nota:'Pueblo Mágico platero.' },
    { name:'Peña de Bernal', url:'https://drive.google.com/thumbnail?id=1MtL8HccDRt1QCiKYEGYjvbqMWefvs0zh&sz=w400', zone:'mexico-centro', nota:'Monolito natural en Querétaro.' },
    { name:'Acueducto Querétaro', url:'https://drive.google.com/thumbnail?id=16IWM61-1g8dMHUjFFOmBSa59lfkNuudj&sz=w400', zone:'mexico-centro', nota:'Símbolo de Querétaro.' },
    { name:'San Miguel Allende', url:'https://drive.google.com/thumbnail?id=1XkCmuyL-CgxRgYYHNH8ALpZ-VsFSbmHz&sz=w400', zone:'mexico-centro', nota:'Ciudad colonial en Guanajuato.' },
    { name:'Guanajuato', url:'https://drive.google.com/thumbnail?id=18p224Z-ZRoPbY0AneK0O1f2NA_o_OlMz&sz=w400', zone:'mexico-centro', nota:'Ciudad minera colorida.' },
    { name:'Catedral de Morelia', url:'https://drive.google.com/thumbnail?id=1E-oVFOgOPzYp4srd4KCqF5P85-7MHggl&sz=w400', zone:'mexico-centro', nota:'Catedral barroca en Michoacán.' },
    { name:'Mariposa Monarca', url:'https://drive.google.com/thumbnail?id=1sjwUvycZ2IFG63tvdAWp6T6R7F-Um4so&sz=w400', zone:'mexico-centro', nota:'Reserva en Michoacán.' },
];
var mexicoSurPhotos = [
    { name:'Monte Albán', url:'https://drive.google.com/thumbnail?id=1gOcZbjPfsR83y7-IIHoAhApP3fyKXEId&sz=w400', zone:'mexico-sur', nota:'Antigua ciudad zapoteca en Oaxaca.' },
    { name:'Hierve el Agua', url:'https://drive.google.com/thumbnail?id=1F510KIRkDEBXmtbQxLyPBfPDwv4eOx1j&sz=w400', zone:'mexico-sur', nota:'Cascadas petrificadas en Oaxaca.' },
    { name:'Árbol del Tule', url:'https://drive.google.com/thumbnail?id=15F0AOK2MRDfCtT2kNZiz-2A9Zt5FWMZG&sz=w400', zone:'mexico-sur', nota:'El árbol más ancho del mundo.' },
    { name:'Cañón del Sumidero', url:'https://drive.google.com/thumbnail?id=1AY-dZyVuAfJUCr5a6XIo6xeSSygLifDF&sz=w400', zone:'mexico-sur', nota:'Imponente cañón en Chiapas.' },
    { name:'San Cristóbal', url:'https://drive.google.com/thumbnail?id=1RTAxi1MUG3Gfn99H-NWZ9u8q9jAw2CHv&sz=w400', zone:'mexico-sur', nota:'Pueblo Mágico colonial.' },
    { name:'Palenque', url:'https://drive.google.com/thumbnail?id=1xv1tCq-CLvPzLmGivPoDgxB6ZaoE6zam&sz=w400', zone:'mexico-sur', nota:'Zona arqueológica maya en Chiapas.' },
    { name:'Cascadas Agua Azul', url:'https://drive.google.com/thumbnail?id=1xdFIvo_2J5oQYP30r7S5i5s6dc_43naK&sz=w400', zone:'mexico-sur', nota:'Cascadas de color turquesa.' },
    { name:'Lagunas Montebello', url:'https://drive.google.com/thumbnail?id=1u3eIcjz79xdFoSumym1kwpa4D-vsKB7Y&sz=w400', zone:'mexico-sur', nota:'Conjunto de lagunas en Chiapas.' },
    { name:'Popocatépetl', url:'https://drive.google.com/thumbnail?id=1M5JkHP-flrWAqAaNKFz12y_6Rr1-DJNF&sz=w400', zone:'mexico-sur', nota:'Volcán activo.' },
    { name:'Catedral de Puebla', url:'https://drive.google.com/thumbnail?id=1DaNTAgluNsp4XpKmombeG0nJIInIU9W3&sz=w400', zone:'mexico-sur', nota:'Catedral renacentista.' },
    { name:'Tepoztlán', url:'https://drive.google.com/thumbnail?id=1261PjaEpx1x1hWlXKxmNXeI18ai8zwlt&sz=w400', zone:'mexico-sur', nota:'Pueblo Mágico en Morelos.' },
    { name:'Grutas Cacahuamilpa', url:'https://drive.google.com/thumbnail?id=1MkwNsgI2pi1AGB1KfWFgQkvzdV45XLVj&sz=w400', zone:'mexico-sur', nota:'Espectaculares grutas en Guerrero.' },
];
  var mexicoCaribePhotos = [
    { name:'Chichén Itzá', url:'https://drive.google.com/thumbnail?id=1jA5Sxah7QbB0rxzar-lGbSvXWhA-reqb&sz=w400', zone:'mexico-caribe', nota:'Maravilla del mundo moderno en Yucatán.' },
    { name:'Tulum', url:'https://drive.google.com/thumbnail?id=12shfaStYT9_agFpZS-ewzD8Jj-tpJaVW&sz=w400', zone:'mexico-caribe', nota:'Ruinas mayas frente al mar Caribe.' },
    { name:'Cenote Ik Kil', url:'https://drive.google.com/thumbnail?id=1L8SBXEY0KStrUCmZAx32S4yOk7AfqtBg&sz=w400', zone:'mexico-caribe', nota:'Cenote sagrado en Yucatán.' },
    { name:'Playa del Carmen', url:'https://drive.google.com/thumbnail?id=1w3OcH6iTq2_oSjTPMPuTqErGFrvVlTQO&sz=w400', zone:'mexico-caribe', nota:'Playas caribeñas en Quintana Roo.' },
    { name:'Isla Mujeres', url:'https://drive.google.com/thumbnail?id=1A-vnc1A5smvuergSKDB2xnLEz-H9NK_V&sz=w400', zone:'mexico-caribe', nota:'Isla paradisíaca en Quintana Roo.' },
    { name:'Cozumel', url:'https://drive.google.com/thumbnail?id=1Dr9EF-zq2fxSe3HEqzRj-xgh3NARdzIq&sz=w400', zone:'mexico-caribe', nota:'Isla caribeña con arrecifes de coral.' },
    { name:'Bacalar', url:'https://drive.google.com/thumbnail?id=1pKRnbbYunsPVwW9jJVE9VErvWu-Z4zkl&sz=w400', zone:'mexico-caribe', nota:'Laguna de los 7 colores en Quintana Roo.' },
    { name:'Uxmal', url:'https://drive.google.com/thumbnail?id=1hAtR0zNioqtQEQgJiGHkmF94lUW3DGBE&sz=w400', zone:'mexico-caribe', nota:'Zona arqueológica maya en Yucatán.' },
    { name:'Mérida', url:'https://drive.google.com/thumbnail?id=1IKaYbeoQRpv73Xrl0cHcGCKPKfNP7X51&sz=w400', zone:'mexico-caribe', nota:'Capital cultural de Yucatán.' },
    { name:'Calakmul', url:'https://drive.google.com/thumbnail?id=1CH7B4Xp--LywDUVrne6hmmg0gIIE1Rr1&sz=w400', zone:'mexico-caribe', nota:'Antigua ciudad maya en Campeche.' },
    { name:'Campeche', url:'https://drive.google.com/thumbnail?id=1vjpTTM_OuwSmHm95edrkDxaOUAICt0PR&sz=w400', zone:'mexico-caribe', nota:'Ciudad amurallada en Campeche.' },
    { name:'Cenote Dos Ojos', url:'https://drive.google.com/thumbnail?id=1FEnFLMCVGyTjnr07me3aFYNlbsKtfLA5&sz=w400', zone:'mexico-caribe', nota:'Cenote famoso para buceo en Quintana Roo.' },
]; },
];
var villarricaPhotos = [
    { name:'Villarrica 1', url:'https://drive.google.com/thumbnail?id=1DtfuiaOzwwNuonJ__siHtNp5bkQrcdvy&sz=w400', nota:'Lago al atardecer.' },
    { name:'Villarrica 2', url:'https://drive.google.com/thumbnail?id=13pgYQFfItKdMXM4I6Z2hTykbhyEqzHSb&sz=w400', nota:'Vista desde Pucón.' },
    { name:'Villarrica 3', url:'https://drive.google.com/thumbnail?id=1U7D4Or9FnEf4OwUpVVzl08Rp9o9JDrjs&sz=w400', nota:'Navegando frente al coloso.' },
    { name:'Villarrica 4', url:'https://drive.google.com/thumbnail?id=15IgWa1AsKjwk7tTRGEO2ro8DTlJbcj--&sz=w400', nota:'Bosques en la Araucanía.' },
    { name:'Villarrica 5', url:'https://drive.google.com/thumbnail?id=1qysQ8h-YHQyh5Mg4opZzsTAmnDQIMG-t&sz=w400', nota:'El rugido del volcán.' },
    { name:'Villarrica 6', url:'https://drive.google.com/thumbnail?id=1LO2MAuNFcdTjhjDPxS5Ousw3HBnVkh-g&sz=w400', nota:'Termas cerca del volcán.' },
    { name:'Villarrica 7', url:'https://drive.google.com/thumbnail?id=183L3Zri6qcm6leHek4j-LulR3hUVomfK&sz=w400', nota:'Amanecer en el lago.' },
    { name:'Villarrica 8', url:'https://drive.google.com/thumbnail?id=1P7m6YU1U2hIQ6KT7jxfs9Smq7bKhnmmO&sz=w400', nota:'El volcán de noche.' },
    { name:'Villarrica 9', url:'https://drive.google.com/thumbnail?id=1Z2-Sxmlpm9hihM-ZNmKUarB2nHyX_Ly9&sz=w400', nota:'Paisajes que enamoran.' },
];
var valparaisoPhotos = [
    { name:'Valpo 1', url:'https://drive.google.com/thumbnail?id=1WM5sd8aZyPDfeoyczNgYRKIRH2GToOJC&sz=w400', nota:'Vista del puerto patrimonial.' },
    { name:'Valpo 2', url:'https://drive.google.com/thumbnail?id=1ZiwDZKB6TyV6vJvqMYeqGCdd5HSNL6nx&sz=w400', nota:'Cerros coloridos.' },
    { name:'Valpo 3', url:'https://drive.google.com/thumbnail?id=1eh776MPiWs6ry44Hd5BFxuZN4cqurNkF&sz=w400', nota:'Calles museo.' },
    { name:'Valpo 4', url:'https://drive.google.com/thumbnail?id=1EWM0KGofQJJ3VX6-iTMnT5K6RGMJwmzq&sz=w400', nota:'Murales porteños.' },
    { name:'Valpo 5', url:'https://drive.google.com/thumbnail?id=1XzDDJ2_a7nHV_owPvLzVxBPax0Bd1OZj&sz=w400', nota:'Ascensores centenarios.' },
    { name:'Valpo 6', url:'https://drive.google.com/thumbnail?id=1Id4QQXiPgqSz0gbKoCTDdTzDP-KPC6Fo&sz=w400', nota:'Casas de colores.' },
    { name:'Valpo 7', url:'https://drive.google.com/thumbnail?id=1Hn9Y4bxYWUqVifIbREzfnsrV40SOKJ9R&sz=w400', nota:'Puerto de poetas.' },
    { name:'Valpo 8', url:'https://drive.google.com/thumbnail?id=1_rqH51EFskHxRpzDIV8fXt9rZLuLem4l&sz=w400', nota:'Atardeceres mágicos.' },
    { name:'Valpo 9', url:'https://drive.google.com/thumbnail?id=1Lq0s16e6S5reutW03wfY2bFaP5ZdLUmB&sz=w400', nota:'Joya del Pacífico.' },
    { name:'Valpo 10', url:'https://drive.google.com/thumbnail?id=1Oj8J0SWtItxwpAEcvaEUo04MlrGUiJcv&sz=w400', nota:'Escaleras al cielo.' },
];

var traditionalTiles = [
    { name:'Bambú 1', symbol:'一' },{ name:'Bambú 2', symbol:'二' },{ name:'Bambú 3', symbol:'三' },
    { name:'Bambú 4', symbol:'四' },{ name:'Bambú 5', symbol:'五' },{ name:'Bambú 6', symbol:'六' },
    { name:'Bambú 7', symbol:'七' },{ name:'Bambú 8', symbol:'八' },{ name:'Bambú 9', symbol:'九' },
    { name:'Carácter 1', symbol:'一' },{ name:'Carácter 2', symbol:'二' },{ name:'Carácter 3', symbol:'三' },
    { name:'Carácter 4', symbol:'四' },{ name:'Carácter 5', symbol:'五' },{ name:'Carácter 6', symbol:'六' },
    { name:'Carácter 7', symbol:'七' },{ name:'Carácter 8', symbol:'八' },{ name:'Carácter 9', symbol:'九' },
    { name:'Círculo 1', symbol:'●' },{ name:'Círculo 2', symbol:'◎' },{ name:'Círculo 3', symbol:'◉' },
    { name:'Círculo 4', symbol:'◯' },{ name:'Círculo 5', symbol:'⬤' },{ name:'Círculo 6', symbol:'⭕' },
    { name:'Círculo 7', symbol:'⚫' },{ name:'Círculo 8', symbol:'🔴' },{ name:'Círculo 9', symbol:'🔵' },
    { name:'Viento Este', symbol:'東' },{ name:'Viento Sur', symbol:'南' },
    { name:'Viento Oeste', symbol:'西' },{ name:'Viento Norte', symbol:'北' },
    { name:'Dragón Rojo', symbol:'中' },{ name:'Dragón Verde', symbol:'發' },{ name:'Dragón Blanco', symbol:'白' },
    { name:'Primavera', symbol:'春' },{ name:'Verano', symbol:'夏' },
    { name:'Otoño', symbol:'秋' },{ name:'Invierno', symbol:'冬' },
    { name:'Ciruelo', symbol:'梅' },{ name:'Orquídea', symbol:'蘭' },
    { name:'Crisantemo', symbol:'菊' },{ name:'Bambú Flor', symbol:'竹' },
];

var ZONES = [
    { id:'norte', name:'NORTE', icon:'🏜️', country:'chile', photos:nortePhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'centro', name:'CENTRO', icon:'🏛️', country:'chile', photos:centroPhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'sur', name:'SUR', icon:'🌋', country:'chile', photos:surPhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'austral', name:'AUSTRAL', icon:'🗻', country:'chile', photos:patagoniaPhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'argentina-norte', name:'ARG NORTE', icon:'🏜️', country:'argentina', photos:argentinaNortePhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'argentina-centro', name:'ARG CENTRO', icon:'🏛️', country:'argentina', photos:argentinaCentroPhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'argentina-patagonia', name:'ARG PATAGONIA', icon:'🗻', country:'argentina', photos:argentinaPatagoniaPhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'argentina-litoral', name:'ARG LITORAL', icon:'🌴', country:'argentina', photos:argentinaLitoralPhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'mexico-norte', name:'MX NORTE', icon:'🏜️', country:'mexico', photos:mexicoNortePhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'mexico-centro', name:'MX CENTRO', icon:'🏛️', country:'mexico', photos:mexicoCentroPhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'mexico-sur', name:'MX SUR', icon:'🌋', country:'mexico', photos:mexicoSurPhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
    { id:'mexico-caribe', name:'MX CARIBE', icon:'🌴', country:'mexico', photos:mexicoCaribePhotos, levels:[ {num:1,pairs:6},{num:2,pairs:8},{num:3,pairs:10},{num:4,pairs:12},{num:5,pairs:14},{num:6,pairs:16},{num:7,pairs:18},{num:8,pairs:20},{num:9,pairs:24},{num:10,pairs:28} ] },
];

var MINIGAMES = {
    'centro-3': { name:'Memorice de Valparaíso', type:'memorice', icon:'🎨', photos: valparaisoPhotos },
    'sur-5': { name:'Memorice de Villarrica', type:'memorice', icon:'🌋', photos: villarricaPhotos },
};
